config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  root 'welcome#index'

  resources :items, only: [:index, :show]

  get '/carts', to: 'carts#show'
  post '/carts', to: 'carts#add'
  patch '/carts', to: 'carts#update'
  delete '/carts', to: 'carts#clear'

  get '/register', to: 'users#new'
  post '/register', to: 'users#create'

  get '/login', to: 'sessions#new', as: :login
  post '/login', to: 'sessions#create'
  get '/logout', to: 'sessions#logout'

  get '/profile', to: 'default/users#show'
  get '/profile/edit', to: 'default/users#edit'
  patch '/profile/edit', to: 'default/users#update'



  scope module: :default, path: :profile do
    resources :orders, only: [:create, :show, :index, :destroy], as: :profile_orders
  end


  get '/merchants', to: 'merchants#index'

  patch 'merchants/items/enable/:id', to: 'merchants/items#enable'
  patch 'merchants/items/disable/:id', to: 'merchants/items#disable'

  get '/dashboard', to: 'merchants/orders#index'
  scope module: 'merchants', path: 'dashboard', as: :dashboard do
    resources :items, only: [:index, :new, :create, :edit, :update, :destroy]
    resources :order_items, only: [:update]
    resources :orders, only: [:show]
  end

  resources :users do
    resources :addresses, only: [:new, :create, :edit, :update, :destroy]
  end


  namespace :admin do
    resources :users, only: [:index, :show]
    get '/dashboard', to: 'users#dashboard'
    get '/merchants/:id', to: 'merchants#show', as: :merchant
    patch '/merchant/edit', to: 'merchants#edit'
    patch '/merchant/enable/:id', to: 'merchants#enable'
    patch '/merchant/disable/:id', to: 'merchants#disable'
    resources :orders, only: [:update]
  end
end

app/models/cart.rb
class Cart
  attr_reader :contents

  def initialize(session)
    @contents = session || Hash.new(0)
  end

  def add(item_id)
    @contents[item_id.to_s] ||= 0
    @contents[item_id.to_s] += 1
  end

  def ids_to_items
    items = {}
    self.contents.each do |item_id, qty|
      items[Item.find(item_id)] = qty
    end
    items
  end

  def total_price
    ids_to_items.sum{|item, qty| item.price * qty}
  end

  def create_order(buyer_id)
    order = Order.new(user_id: buyer_id, status: 1)
    ids_to_items.each do |item, qty|
      oi = OrderItem.new(item: item, order: order, quantity: qty, price: item.price, fulfilled: false )
      oi.save
    end
    order.save
  end
end

app/controllers/carts_controller.rb
class CartsController < ApplicationController

  before_action :cart_user?

  def show
    @user = current_user
    cart = Cart.new(session[:cart])
    @cart_items = cart.ids_to_items
    @cart_price_total = cart.total_price
  end

  def update
    request = params[:request]
    item_id = params[:id]
    cart = session[:cart]
    if request == "remove_item"
      cart.delete(item_id)
    elsif request == "add_one"
      cart[item_id] += 1
    elsif request == "remove_one"
      cart[item_id] -= 1
      cart.delete(item_id) if cart[item_id] == 0
    end

    redirect_to carts_path
  end

  def add
    item = Item.find(params[:item_id])
    cart = Cart.new(session[:cart])
    cart.add(item.id)
    session[:cart] = cart.contents
    flash.notice = "#{item.name} has been added to your cart"
    redirect_to items_path
  end

  def clear
    session[:cart] = {}
    redirect_to carts_path
  end

  private

  def cart_user?
    render file: "/public/404" unless !current_admin? && !current_merchant?
  end
end

app/views/carts/show.html.erb
<% if current_user.nil? %>
  <p>You must <%= link_to 'register', register_path %> or <%= link_to 'login', login_path %> to checkout.</p>
<% end %>

<% if @user %>
  <h1 id='cart-header' class="text-center"><%= @user.name %>'s Cart</h1>
<% else %>
  <h1 id='cart-header' class="text-center">Visitor's Cart</h1>
<% end %>

<table class="table">
  <thead class="thead-dark">
    <tr class="text-center">
      <th scope="col">Cheese</th>
      <th scope="col">Quantity</th>
      <th scope="col">Seller</th>
      <th scope="col">Price</th>
      <th scope="col">Item Total</th>
      <th scope="col" colspan="4"></th>
    </tr>
  </thead>
  <tbody>
    <% if @cart_items.empty? %>
      <p>Your cart is currently empty.</p>
    <% else %>
      <% @cart_items.each do |item, qty| %>
        <section id='item-<%= item.id %>'>
          <tr class="text-center">
            <td class='align-middle'><%= item.name %></td>
            <td class='align-middle'>
              <%= qty %>
            </td>
            <td class='align-middle'><%= item.user.name %></td>
            <td class='align-middle'><%= number_to_currency(item.price) %></td>
            <td class='align-middle'><%= number_to_currency(item.price * qty) %></td>
            <td class='align-middle'><%= link_to "Remove Item", carts_path({id: item.id, request: :remove_item}), method: :patch %>
            <td class='align-middle'><%= link_to "Add One", carts_path({id: item.id, request: :add_one}), method: :patch %>
            <td class='align-middle'><%= link_to "Remove One", carts_path({id: item.id, request: :remove_one}), method: :patch %>
            <td class='align-middle'><img class='cart-img' src='<%= item.image %>'></td>
          </tr>
        </section>
      <% end %>
    <% end %>
      <tr class='text-center' id='cart_total'>
        <td></td>
        <td></td>
        <td></td>
        <td>Total: </td>
        <td colspan="5"><%= number_to_currency(@cart_price_total) %></td>
      </tr>
  </tbody>
</table>
<% if !current_user.nil? && !current_admin? && !current_merchant? %>
  <h5 class='text-center'><%= link_to "Checkout", profile_orders_path, method: :post, style:"font-size:35px;" %></h5>
<% end %>
<h5 class='text-center'><%= link_to "Clear Cart", carts_path, method: :delete %></h5>