config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  root 'welcome#index'

  resources :items, only: [:index, :show]

  get '/carts', to: 'carts#show'
  post '/carts', to: 'carts#add'
  patch '/carts', to: 'carts#update'
  delete '/carts', to: 'carts#clear'

  get '/register', to: 'users#new'
  post '/register', to: 'users#create'

  get '/login', to: 'sessions#new', as: :login
  post '/login', to: 'sessions#create'
  get '/logout', to: 'sessions#logout'

  get '/profile', to: 'default/users#show'
  get '/profile/edit', to: 'default/users#edit'
  patch '/profile/edit', to: 'default/users#update'



  scope module: :default, path: :profile do
    resources :orders, only: [:create, :show, :index, :destroy], as: :profile_orders
  end


  get '/merchants', to: 'merchants#index'

  patch 'merchants/items/enable/:id', to: 'merchants/items#enable'
  patch 'merchants/items/disable/:id', to: 'merchants/items#disable'

  get '/dashboard', to: 'merchants/orders#index'
  scope module: 'merchants', path: 'dashboard', as: :dashboard do
    resources :items, only: [:index, :new, :create, :edit, :update, :destroy]
    resources :order_items, only: [:update]
    resources :orders, only: [:show]
  end

  resources :users do
    resources :addresses, only: [:new, :create, :edit, :update, :destroy]
  end


  namespace :admin do
    resources :users, only: [:index, :show]
    get '/dashboard', to: 'users#dashboard'
    get '/merchants/:id', to: 'merchants#show', as: :merchant
    patch '/merchant/edit', to: 'merchants#edit'
    patch '/merchant/enable/:id', to: 'merchants#enable'
    patch '/merchant/disable/:id', to: 'merchants#disable'
    resources :orders, only: [:update]
  end
end

app/models/item.rb
class Item < ApplicationRecord
  belongs_to :user
  has_many :order_items
  has_many :orders, through: :order_items


  validates_presence_of :name, :price, :description, :image, :inventory
  validates :price, :numericality => { :greater_than => 0 }
  validates :inventory, :numericality => { :greater_than => 0 }
  validates_inclusion_of :active, in: [true, false]

  def self.all_active
    where(active: true)
  end

  def self.most_5_bought
    self.joins(:order_items)
        .select('sum(quantity) AS order_quantity, items.*')
        .where('order_items.fulfilled=true')
        .group(:id)
        .order('order_quantity desc')
        .limit(5)
  end

  def self.least_5_bought
    self.joins(:order_items)
        .select('sum(quantity) AS order_quantity, items.*')
        .where('order_items.fulfilled=true')
        .group(:id)
        .order('order_quantity')
        .limit(5)
  end

  def average_days_to_fulfill
    order_items.where(fulfilled: true).average("order_items.updated_at - order_items.created_at")
  end
end

app/controllers/admin/merchants_controller.rb
class Admin::MerchantsController < Admin::BaseController

  def show
    @user = User.find_by(id: params[:id])

    if @user.role == "default"
      redirect_to admin_user_path(@user.id)
    else
      @orders = @user.pending_orders

      render template: "merchants/orders/index"
    end
  end

  def edit
    user = User.find_by(id: params[:id])
    request = params[:request]
    if request == 'upgrade_to_merchant'
      User.update(user.id, role: :merchant)
      flash[:notice] = "User #{user.name} has been promoted to Merchant"
      redirect_to "/admin/merchants/#{user.id}"
    elsif request == 'downgrade_to_user'
      User.update(user.id, role: :default)
      flash[:notice] = "User #{user.name} has been demoted to Default"
      redirect_to admin_user_path(user.id)
    end
  end

  def disable
    user = User.find_by(id: params[:id])
    if User.update(user.id, active: false)
      flash[:notice] = "Merchant's account is now disabled"
    end
    redirect_to merchants_path
  end

  def enable
    user = User.find_by(id: params[:id])
    if User.update(user.id, active: true)
      flash[:notice] = "Merchant's account is now enabled"
    end
    redirect_to merchants_path
  end
end

app/controllers/items_controller.rb
class ItemsController < ApplicationController

  def index
    @items = Item.all_active
    @most_5_bought_items = Item.most_5_bought
    @least_5_bought_items = Item.least_5_bought
  end

  def show
    @item = Item.find_by(id: params['id'])
  end
end

app/controllers/merchants/base_controller.rb
class Merchants::BaseController < ApplicationController
  before_action :require_merchant

  def require_merchant
    render file: "/public/404" unless current_merchant?
  end
end

app/controllers/merchants/items_controller.rb
class Merchants::ItemsController < Merchants::BaseController
  def index
    @merchant = User.find(current_user.id)
  end

  def new
    @merchant = User.find(current_user.id)
    @item = @merchant.items.new
  end

  def create
    verify_image(params)
    @merchant = User.find(current_user.id)
    @item = @merchant.items.new(items_params)
    if @item.save
      flash[:notice] = "The item was created successfully."
      redirect_to dashboard_items_path
    else
      render :new
    end
  end

  def edit
    @merchant = current_user
    @item = @merchant.items.find(params[:id])
  end

  def update
    verify_image(params)
    @merchant = current_user
    @item = @merchant.items.find(params[:id])
    @item.update(items_params)
    if @item.save
      flash[:notice] = "The item was updated."
      redirect_to dashboard_items_path
    else
      render :new
    end
  end

  def disable
    @item = Item.find(params[:id])
    @item.active = false
    @item.save
    flash[:notice] = "This item has been disabled."
    redirect_to dashboard_items_path
  end

  def enable
    @item = Item.find(params[:id])
    @item.active = true
    @item.save
    flash[:notice] = "This item has been enabled."
    redirect_to dashboard_items_path
  end

  def destroy
    @item = Item.destroy(params[:id])
    flash[:notice] = "Item #{@item.id} is now deleted."
    redirect_to dashboard_items_path
  end

  private

  def items_params
    params.require(:item).permit(:name, :price, :description, :image, :inventory )
  end

  def verify_image(params)
    if params["item"]["image"] == ""
      params["item"]["image"] = "https://kaaskraam.com/wp-content/uploads/2018/02/Gouda-Belegen.jpg"
    end
  end

end

app/controllers/merchants/order_items_controller.rb
class Merchants::OrderItemsController < Merchants::BaseController
  def update
    order_item = OrderItem.find(params[:id])
    order = Order.find(order_item.order_id)

    order_item.update(fulfilled: true)
    flash[:notice] = "Item '#{order_item.item.name}' fulfilled."

    redirect_to dashboard_order_path(order)
  end
end

app/controllers/merchants/orders_controller.rb
class Merchants::OrdersController < Merchants::BaseController
  def show
    @merchant = current_user
    @order = Order.find(params[:id])
    @user = @order.user
    @order_items = @order.order_items.map {|order_item| order_item if order_item.item.user_id == @merchant.id}.compact
  end

  def index
    @user = current_user
    @orders = @user.pending_orders
  end
end

app/controllers/merchants_controller.rb
class MerchantsController < ApplicationController

  def index
    @merchants = User.all_active_merchants if !current_admin?
    @merchants = User.where(role: :merchant) if current_admin?
    @top_merchants = User.top_3_merchants_by_sales
    @fastest_merchants = User.fastest_3_fulfilling_merchants
    @slowest_merchants = User.slowest_3_fulfilling_merchants
    @top_3_states_by_order = User.top_3_states
    @top_3_cities_by_order = User.top_3_cities
    @biggest_orders = Order.biggest_3
  end
end

app/views/merchants/items/edit.html.erb
<%= form_for [@merchant, @item], :url => dashboard_item_path(@item.id), method: :patch  do |f| %>

<h2>Edit <%= @item.name %>'s Information</h2>

<p><%= f.label :name %></p>
<%= f.text_field :name %>

<p><%= f.label :description %></p>
<%= f.text_field :description %>

<p><%= f.label :image %></p>
<%= f.text_field :image %>

<p><%= f.label :price %></p>
<%= f.number_field :price, min: 0 %>

<p><%= f.label :inventory %></p>
<%= f.number_field :inventory, min: 0 %>

<%= f.submit "Edit Item" %>

<% end %>

app/views/merchants/items/index.html.erb
<%= link_to 'Add a new item', new_dashboard_item_path %>

<div class="card-group">
  <% @merchant.items.each do |item| %>
    <section id='item-<%= item.id %>'>
      <div class="card" style="width: 18rem;">
        <a class='img-link' href="<%= item_path(item) %>">
          <img class="card-img-top" src="<%= item.image %>" alt="Card image cap">
        </a>
        <div class="card-body">
          <h5 class="card-title"><%= link_to item.name, item_path(item) %></h5>
        </div>
        <ul class="list-group list-group-flush">
          <li class="list-group-item">Item Id: <%= item.id %></li>
          <li class="list-group-item">Inventory: <%= item.inventory %></li>
          <li class="list-group-item">Price: $<%= item.price %><br></li>
        </ul>
        <%= link_to "Edit this item", edit_dashboard_item_path(item.id) %>
        <% if item.orders.empty? %>
          <%= link_to "Delete this item", dashboard_item_path(item), method: :delete %>
        <% end %>
        <% if item.active == true %>
          <%= link_to "Disable this item", "/merchants/items/disable/#{item.id}", :method=> :patch %>
        <% else %>
          <%= link_to "Enable this item", "/merchants/items/enable/#{item.id}", :method=> :patch %>
        <% end %>
      </div>
    </section>
  <% end %>
</div>

app/views/merchants/items/new.html.erb
<% @item.errors.full_messages.each do |msg| %>
  <%= msg %><br>
<% end %>

<%= form_for [@merchant, @item], :url => "/dashboard/items" do |f| %>

<%= f.label :name %>
<%= f.text_field :name %>

<%= f.label :description %>
<%= f.text_area :description %>

<%= f.label :image %>
<%= f.text_field :image %>

<%= f.label :price %>
<%= f.number_field :price, min: 0, step: 0.01 %>

<%= f.label :inventory %>
<%= f.number_field :inventory, min: 0  %>

<%= f.submit %>

<% end %>