config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  root 'welcome#index'

  resources :items, only: [:index, :show]

  get '/carts', to: 'carts#show'
  post '/carts', to: 'carts#add'
  patch '/carts', to: 'carts#update'
  delete '/carts', to: 'carts#clear'

  get '/register', to: 'users#new'
  post '/register', to: 'users#create'

  get '/login', to: 'sessions#new', as: :login
  post '/login', to: 'sessions#create'
  get '/logout', to: 'sessions#logout'

  get '/profile', to: 'default/users#show'
  get '/profile/edit', to: 'default/users#edit'
  patch '/profile/edit', to: 'default/users#update'



  scope module: :default, path: :profile do
    resources :orders, only: [:create, :show, :index, :destroy], as: :profile_orders
  end


  get '/merchants', to: 'merchants#index'

  patch 'merchants/items/enable/:id', to: 'merchants/items#enable'
  patch 'merchants/items/disable/:id', to: 'merchants/items#disable'

  get '/dashboard', to: 'merchants/orders#index'
  scope module: 'merchants', path: 'dashboard', as: :dashboard do
    resources :items, only: [:index, :new, :create, :edit, :update, :destroy]
    resources :order_items, only: [:update]
    resources :orders, only: [:show]
  end

  resources :users do
    resources :addresses, only: [:new, :create, :edit, :update, :destroy]
  end


  namespace :admin do
    resources :users, only: [:index, :show]
    get '/dashboard', to: 'users#dashboard'
    get '/merchants/:id', to: 'merchants#show', as: :merchant
    patch '/merchant/edit', to: 'merchants#edit'
    patch '/merchant/enable/:id', to: 'merchants#enable'
    patch '/merchant/disable/:id', to: 'merchants#disable'
    resources :orders, only: [:update]
  end
end

app/models/user.rb
class User < ApplicationRecord
  has_many :items
  has_many :orders
  has_many :addresses

  validates_presence_of :password_digest, :name

  validates :email, presence: true, uniqueness: true

  has_secure_password

  enum role: ["default", "merchant", "admin"]

  def best_customer_items
    order = OrderItem.joins("JOIN orders ON orders.id=order_items.order_id")
             .joins(('JOIN users ON users.id=orders.user_id'))
             .joins('JOIN items ON items.id=order_items.item_id')
             .where("orders.status=2 AND items.user_id=#{self.id}")
             .select('sum(order_items.quantity) AS total_bought, users.id as user_id, users.*')
             .group('users.id')
             .order('total_bought desc')
             .limit(1)
  end

  def best_customer_orders
    Order.where("orders.status = 2")
      .joins(items: :order_items)
      .joins(:user)
      .where("items.user_id = ?", self.id)
      .select("orders.user_id, COUNT(DISTINCT(order_items.order_id)) AS order_count")
      .group("orders.user_id")
      .order("order_count DESC")
      .limit(1)
  end

  def top_3_city_state
    self.items
        .joins(:orders)
        .joins("JOIN users ON users.id = orders.user_id")
        .where("orders.status=2")
        .select("sum(order_items.quantity) AS total_ordered, users.state, users.city")
        .group("users.state")
        .group("users.city")
        .order("total_ordered desc")
        .limit(3)
  end

 def top_3_states
    User.select("users.state, sum(order_items.quantity) AS total_ordered")
    .joins(orders: :items)
    .where("orders.status = 2 AND items.user_id = #{self.id} ")
    .group("users.state")
    .order("total_ordered DESC")
    .limit(3)
  end

  def top_items_sold(limit)
    Item.joins(:user, :orders)
        .where("orders.status = 2 AND items.user_id = #{self.id}")
        .select("items.*, sum(order_items.quantity) AS total_ordered")
        .group("items.id")
        .order('total_ordered DESC')
        .limit(limit)
  end

  def items_sold
    User.joins(items: :orders)
      .where("orders.status = 2 AND items.user_id = #{self.id}")
      .select("users.*, sum(order_items.quantity) AS total_ordered, sum(items.inventory) AS total_inventory")
      .group("users.id")
      .first
      .total_ordered
  end

  def total_items_count
    items.sum(:inventory) + self.items_sold
  end

  def items_sold_percentage
    items_sold / total_items_count.to_f
  end

  def self.email_string
    pluck(:email)
  end

  def self.all_active_merchants
    where('active=true AND role=1')
  end

  def pending_orders
    Order.joins(:items).
          where("items.user_id = #{self.id} AND orders.status = 1").
          distinct(:orders)
  end

  def self.top_3_merchants_by_sales
    self.joins(items: :order_items)
        .joins('JOIN orders ON order_items.order_id=orders.id')
        .select('sum(order_items.price * order_items.quantity) AS revenue, users.*')
        .where('users.role=1 AND users.active=true AND orders.status=2')
        .group('users.id')
        .order('revenue desc')
        .limit(3)
  end

  def self.fastest_3_fulfilling_merchants
    self.joins(items: :order_items)
        .joins('JOIN orders ON order_items.order_id=orders.id')
        .where("users.role=1 AND users.active=true AND orders.status=2")
        .select('sum(order_items.updated_at - order_items.created_at) AS fulfillment_time, users.*')
        .group(:id)
        .order('fulfillment_time')
        .limit(3)
  end

  def self.slowest_3_fulfilling_merchants
    self.joins(items: :order_items)
        .joins('JOIN orders ON order_items.order_id=orders.id')
        .where('users.role=1 AND users.active=true AND orders.status=2')
        .select('sum(order_items.updated_at - order_items.created_at) AS fulfillment_time, users.*')
        .group(:id)
        .order('fulfillment_time desc')
        .limit(3)
  end

  def self.top_3_states
    self.joins(items: :order_items)
        .joins('JOIN orders ON order_items.order_id=orders.id')
        .select('count(orders.*), users.state')
        .where('orders.status=2 AND users.role=1')
        .group(:state)
        .order(count: :desc)
        .limit(3)
  end

  def self.top_3_cities
    self.joins(items: :order_items)
        .joins('JOIN orders ON order_items.order_id=orders.id')
        .select('count(orders.*), users.state, users.city')
        .where('orders.status=2 AND users.role=1')
        .group(:state)
        .group(:city)
        .order(count: :desc)
        .limit(3)
  end

  def top_users
OrderItem.joins('JOIN orders ON orders.id=order_items.order_id')
         .joins('JOIN items ON items.id=order_items.item_id')
         .joins('JOIN users ON users.id=orders.user_id')
         .where("orders.status=2 AND items.user_id=#{self.id}")
         .select('sum(order_items.quantity * order_items.price) AS total_spent, users.name, users.id')
         .group('users.id')
         .order('total_spent desc')
  end
end

app/controllers/admin/users_controller.rb
class Admin::UsersController < Admin::BaseController
  def index
    @default_users = User.where(role: :default)
  end

  def show
    @user = User.find_by(id: params[:id])
    if @user.role == "merchant"
      redirect_to "/admin/merchants/#{@user.id}"
    end
  end

  def dashboard
    @user = current_user
    @orders = Order.order(:status)
  end
end

app/controllers/default/users_controller.rb
class Default::UsersController < Default::BaseController
  def show
    @user = current_user
  end

  def edit
    @user = current_user
  end

  def update
    @user = current_user
    if password_confirmation != true
      flash.now[:notice] = "Those passwords don't match."
      render :edit
    elsif email_confirmation(@user.email) == true
      flash[:notice] = "Email has already been taken"
      render :edit
    elsif @user.update(user_params)
      flash[:notice] = "Your information has been updated!"
      redirect_to profile_path
    else
      render :edit
    end
  end

  private

  def email_confirmation(user_email = nil)
    (User.email_string - [user_email]).include?(params[:user][:email])
  end

  def password_confirmation
    if params["user"]["password"] == params["user"]["confirm_password"]
      true
    else
      false
    end
  end

  def user_params
    params.require(:user).permit(:name, :address, :city, :state, :zip, :email, :password)
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController

  def new
    @user = User.new
  end

  def create
    @user = User.new(user_params)
    @address = @user.addresses.new(address_params)
    @address.nickname = "home"
    if password_confirmation != true
      flash.now[:notice] = "Those passwords don't match."
      render :new
    elsif @user.save
      session[:user_id] = @user.id
      flash[:notice] = "You are now registered and logged in."
      redirect_to profile_path
    else
      render :new
    end
  end

  private

  def password_confirmation
    if params["user"]["password"] == params["user"]["confirm_password"]
      true
    else
      false
    end
  end

  def user_params
    params.require(:user).permit(:name, :address, :city, :state, :zip, :email, :password)
  end

  def address_params
    params.require(:user).require(:address).permit(:street, :city, :state, :zip)
  end

end

app/views/admin/users/dashboard.html.erb
<div id="content-wrapper">
  <div class="container-fluid">
    <div class="card mb=12">
      <div class="card-header">
        <%= @user.name %> details
      </div>
      <div class="card-body">
        <div class="content">
          <p>Email: <%= @user.email.titlecase %></p>
          <p>Role: <%= @user.role.titlecase %></p>
          <p>Active: <%= @user.active %></p>
          <p>Address: <%= @user.address.titlecase %></p>
          <p>City: <%= @user.city.titlecase %></p>
          <p>State: <%= @user.state.titlecase %></p>
          <p>Zip Code: <%= @user.zip.titlecase %></p>
        </div>
      </div>
    </div>

    <div class="card mb-3">
      <div class="card-header">
        Orders Table
      </div>
      <div class="card-body">
        <div class="table-responsive">
          <table class="table table-bordered" id="dataTable" width="100%" cellspacing="0">
            <thead>
              <tr>
                <th>Order #</th>
                <th>Placed By</th>
                <th>Date placed</th>
                <th>Order Status</th>
                <%# <th>Delete Order</th> %>
              </tr>
            </thead>
            <tbody>
              <% @orders.each do |order| %>
                <tr id="order-<%= order.id %>">
                  <td><%= order.id  %></td>
                  <td><%= order.user.name %></td>
                  <td><%= order.created_at.strftime("%b %d, %Y") %></td>
                  <td><%= order.status.titlecase %><%= + ": Ready to ship!" if order.status == "packaged" %><%= button_to "Ship Order", admin_order_path(order), method: "patch" if order.status == "packaged" %></td>
                  <%# <td><%= button_to "Delete Order", root_path, class:"btn btn-primary" /td> %>
                </tr>
              <% end %>
            </tbody>
          </table>
        </div>
      </div>
    </div>
  </div>
</div>

app/views/admin/users/index.html.erb
<div id="content-wrapper">
  <div class="container-fluid">
    <div class="card mb-3">
      <div class="card-header">
        <i class="fas fa-table"></i>
        Default Users Table
      </div>
      <div class="card-body">
        <div class="table-responsive">
          <table class="table table-bordered" id="dataTable" width="100%" cellspacing="0">
            <thead>
              <tr>
                <th>Name</th>
                <th>Email</th>
                <th>Date Joined</th>
                <th>Promote</th>
              </tr>
            </thead>
            <tbody>
              <% @default_users.each do |user| %>
                <tr id="user-<%= user.id %>">
                  <td><%= link_to user.name, admin_user_path(user.id) %></td>
                  <td><%= user.email %></td>
                  <td><%= user.created_at %></td>
                  <td><%= button_to "Upgrade to Merchant", admin_merchant_edit_path({id: user.id, request: :upgrade_to_merchant}), :method => :patch, class:"btn btn-primary" %></td>
                </tr>
              <% end %>
            </tbody>
          </table>
        </div>
      </div>
    </div>
  </div>  
</div>

app/views/admin/users/show.html.erb
<h2><%= @user.name %></h2>

<p>Email: <%= @user.email %></p>
<p>Role: <%= @user.role %></p>
<p>Active: <%= @user.active %></p>
<p>Address: <%= @user.address %></p>
<p>City: <%= @user.city %></p>
<p>State: <%= @user.state %></p>
<p>Zip Code: <%= @user.zip %></p>

<%= link_to "Upgrade to Merchant", admin_merchant_edit_path({id: @user.id, request: :upgrade_to_merchant}), :method => :patch, class:"btn btn-primary" %>

<% if @user.orders.length > 0 %>
  <%= link_to "View Customers Orders", root_path %>
<% end %>