config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  root 'welcome#index'

  resources :items, only: [:index, :show]

  get '/carts', to: 'carts#show'
  post '/carts', to: 'carts#add'
  patch '/carts', to: 'carts#update'
  delete '/carts', to: 'carts#clear'

  get '/register', to: 'users#new'
  post '/register', to: 'users#create'

  get '/login', to: 'sessions#new', as: :login
  post '/login', to: 'sessions#create'
  get '/logout', to: 'sessions#logout'

  get '/profile', to: 'default/users#show'
  get '/profile/edit', to: 'default/users#edit'
  patch '/profile/edit', to: 'default/users#update'



  scope module: :default, path: :profile do
    resources :orders, only: [:create, :show, :index, :destroy], as: :profile_orders
  end


  get '/merchants', to: 'merchants#index'

  patch 'merchants/items/enable/:id', to: 'merchants/items#enable'
  patch 'merchants/items/disable/:id', to: 'merchants/items#disable'

  get '/dashboard', to: 'merchants/orders#index'
  scope module: 'merchants', path: 'dashboard', as: :dashboard do
    resources :items, only: [:index, :new, :create, :edit, :update, :destroy]
    resources :order_items, only: [:update]
    resources :orders, only: [:show]
  end

  resources :users do
    resources :addresses, only: [:new, :create, :edit, :update, :destroy]
  end


  namespace :admin do
    resources :users, only: [:index, :show]
    get '/dashboard', to: 'users#dashboard'
    get '/merchants/:id', to: 'merchants#show', as: :merchant
    patch '/merchant/edit', to: 'merchants#edit'
    patch '/merchant/enable/:id', to: 'merchants#enable'
    patch '/merchant/disable/:id', to: 'merchants#disable'
    resources :orders, only: [:update]
  end
end

app/models/order.rb
class Order < ApplicationRecord
  belongs_to :user
  has_many :order_items
  has_many :items, through: :order_items

  validates_presence_of :status

  enum status: [:packaged, :pending, :shipped, :cancelled]

  def date_made
    created_at.strftime("%B %-d, %Y")
  end

  def last_updated
    updated_at.strftime("%B %-d, %Y")
  end

  def item_count
    items.count
  end

  def grand_total
    order_items.sum do |item|
      item.price * item.quantity
    end
  end

  def check_fulfillments
    if order_items.all? {|order_item| order_item.fulfilled}
      update(status: :packaged)
    end
  end

  def self.biggest_3
    self.joins(:items)
        .select('count(items.id), orders.*')
        .where('orders.status=2')
        .group(:id)
        .order(count: :desc)
        .limit(3)
  end
end

app/controllers/admin/orders_controller.rb
class Admin::OrdersController < Admin::BaseController
  def update
    @order = Order.find(params[:id])
    @order.update(status: :shipped)

    redirect_to admin_dashboard_path
  end
end

app/controllers/default/base_controller.rb
class Default::BaseController < ApplicationController
  before_action :require_user

  def require_user
    render file: "/public/404" unless current_default?
  end
end

app/controllers/default/orders_controller.rb
class Default::OrdersController < Default::BaseController
  def index
    @user = current_user
    @orders = @user.orders
  end

  def show
    @order = Order.find(params[:id])
    @order_items = @order.order_items
  end

  def destroy
    @order = Order.find(params[:id])
    @order.update(status: :cancelled)
    @order.order_items.each do |order_item|
      order_item.update(fulfilled: false)
    end
    flash[:notice] = "#{@order.id} has been cancelled."

    redirect_to profile_orders_path
  end

  def create
    cart = Cart.new(session[:cart])
    if cart.contents.empty?
      carts_path
    else
      cart.create_order(current_user.id)
      session[:cart] = {}
      flash.notice = "Your Order Was Created"
      redirect_to profile_orders_path
    end
  end
end

app/controllers/default/users_controller.rb
class Default::UsersController < Default::BaseController
  def show
    @user = current_user
  end

  def edit
    @user = current_user
  end

  def update
    @user = current_user
    if password_confirmation != true
      flash.now[:notice] = "Those passwords don't match."
      render :edit
    elsif email_confirmation(@user.email) == true
      flash[:notice] = "Email has already been taken"
      render :edit
    elsif @user.update(user_params)
      flash[:notice] = "Your information has been updated!"
      redirect_to profile_path
    else
      render :edit
    end
  end

  private

  def email_confirmation(user_email = nil)
    (User.email_string - [user_email]).include?(params[:user][:email])
  end

  def password_confirmation
    if params["user"]["password"] == params["user"]["confirm_password"]
      true
    else
      false
    end
  end

  def user_params
    params.require(:user).permit(:name, :address, :city, :state, :zip, :email, :password)
  end
end

app/controllers/merchants/orders_controller.rb
class Merchants::OrdersController < Merchants::BaseController
  def show
    @merchant = current_user
    @order = Order.find(params[:id])
    @user = @order.user
    @order_items = @order.order_items.map {|order_item| order_item if order_item.item.user_id == @merchant.id}.compact
  end

  def index
    @user = current_user
    @orders = @user.pending_orders
  end
end

app/controllers/orders_controller.rb
class OrdersController < ApplicationController
  def index
    @user = current_user
    @orders = @user.orders
  end

  def show
    @order = Order.find(params[:id])
    @order_items = @order.order_items
  end

  def destroy
    @order = Order.find(params[:id])
    @order.update(status: :cancelled)
    @order.order_items.each do |order_item|
      order_item.update(fulfilled: false)
    end
    flash[:notice] = "#{@order.id} has been cancelled."

    redirect_to profile_orders_path
  end

  def create
    cart = Cart.new(session[:cart])
    cart.create_order(current_user.id)
    session[:cart] = {}
    flash.notice = "Your Order Was Created"
    redirect_to profile_orders_path
  end
end

app/views/default/orders/index.html.erb
<h2><%= @user.name %>'s Orders</h2>

<% if @orders.count > 0 %>
  <% @orders.each do |order| %>
    <section id="order-<%= order.id %>">
      <%= link_to "Order ID: #{order.id}", profile_order_path(order) %>
      <p>Date Made: <%= order.date_made %></p>
      <p>Last Updated: <%= order.last_updated %></p>
      <p>Current Status: <%= order.status.capitalize %></p>
      <p>Number of Items: <%= order.item_count %></p>
      <p>Grand Total: <%= number_to_currency(order.grand_total, unit: "$") %></p>
    </section>
  <% end %>
<% else %>
  <p>You haven't made any orders yet!</p>
<% end %>

app/views/default/orders/show.html.erb
<h2>Order <%= @order.id %></h2>

<p>Date Made: <%= @order.date_made %></p>
<p>Last Updated: <%= @order.last_updated %></p>
<p>Current Status: <%= @order.status.capitalize %></p>

<% @order_items.each do |order_item| %>
  <section id="order-item-<%= order_item.id %>">
    <% item = order_item.item %>
    <p><%= link_to "#{item.name}", item_path(item) %></p>
    <p><%= item.description %></p>
    <img src="<%= item.image %>" alt="<%= item.name %> Image">
    <p>Quantity: <%= order_item.quantity %></p>
    <p>Subtotal: <%= number_to_currency(order_item.sub_total, unit: "$") %></p>
  </section>
<% end %>

<p>Number of Items: <%= @order.item_count %></p>
<p>Grand Total: <%= number_to_currency(@order.grand_total, unit: "$") %></p>


<%= button_to "Cancel Order", profile_order_path(@order), method: "delete", disabled: !@order.pending? %>
<% if !@order.pending? %>
  <p>You can only cancel orders that are pending!</p>
<% end %>